---
version: '3'

env:
  CGO_ENABLED: 0

tasks:
  test:
    summary: Run tests
    cmds:
      - task: test-deps-up
      - task: test-run
      - task: test-deps-down

  test-deps-up:
    summary: Starts test dependencies
    cmds:
      - cmd: docker compose up --detach --wait

  test-deps-down:
    summary: Stops test dependencies
    cmds:
      - cmd: docker compose down -v

  test-run:
    summary: Runs tests, must have dependencies running in the docker compose
    cmds:
      - cmd: go test -timeout 2m -cover -coverprofile=coverage.txt -covermode=atomic ./...
    vars:
      PG_HOST:
        sh: docker compose port postgres 5432
    env:
      TEST_POSTGRES: 'postgres://test:test@{{.PG_HOST}}/test?sslmode=disable'

  spell-lint:
    summary: Check spelling
    vars:
      CURDIR:
        sh: pwd
    cmds:
      - cmd: |
          docker run \
            --interactive --tty --rm \
            --volume "{{.CURDIR}}:/workdir" \
            --workdir "/workdir" \
            python:3.12-slim bash -c "python -m pip install --upgrade pip && pip install 'codespell>=2.2.4' && codespell"

  lint:
    summary: Lint the code (expects golangci-lint to be installed)
    cmds:
      - cmd: golangci-lint run --config=./.github/linters/.golangci.yml --fix
