---
version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - revive
    - unconvert
  settings:
    errcheck:
      check-blank: true
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - gosec
          - staticcheck
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vgarvardt/gue)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
